FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    yfinance \
    pandas==2.2.2 \
    minio==7.2.7 \
    requests==2.32.3 \
    requests-cache==1.2.1

COPY collector.py .

CMD ["python", "collector.py"]
